{{define "header"}}
// Code generated by lens-gen. DO NOT EDIT.
package {{ .PackageName }}

import (
	{{- if .IsDynamic }}
	"fmt"
	{{- end }}
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)
{{end}}